" ####
" # VIM default configuration
" ####

" Always show line numbers.
set number

" Highlight current line
set cursorline

" Display file title in title bar
set title

" Tabs indent only 2 spaces
set tabstop=2

" Emoji shortcuts
ab :be: 🇧🇪
ab :white_check_mark: ✅
ab :es: 🇪🇸
